// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.catmq.protocol.service;

public interface CreateSegmentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateSegmentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 segmentId = 1;</code>
   * @return The segmentId.
   */
  long getSegmentId();
}
