// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.catmq.protocol.service;

public interface SendMessage2StorerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendMessage2StorerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes body = 1;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
