// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.catmq.protocol.service;

public interface SendMessage2StorerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendMessage2StorerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgId = 2;</code>
   * @return The msgId.
   */
  java.lang.String getMsgId();
  /**
   * <code>string msgId = 2;</code>
   * @return The bytes for msgId.
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <code>bytes body = 3;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
