// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.catmq.protocol.service;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendMessage2BrokerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendMessage2BrokerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendMessage2BrokerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendMessage2BrokerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetMessageFromBrokerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetMessageFromBrokerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetMessageFromBrokerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetMessageFromBrokerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateTopicRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateTopicRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateTopicResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateTopicResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\032\020definition.proto\"O\n\031Sen" +
      "dMessage2BrokerRequest\022\017\n\007message\030\001 \001(\t\022" +
      "\r\n\005topic\030\002 \001(\t\022\022\n\nproducerId\030\003 \001(\003\"O\n\032Se" +
      "ndMessage2BrokerResponse\022\013\n\003ack\030\001 \001(\010\022\013\n" +
      "\003res\030\002 \001(\t\022\027\n\006status\030\003 \001(\0132\007.Status\"Q\n\033G" +
      "etMessageFromBrokerRequest\022\017\n\007message\030\001 " +
      "\001(\t\022\r\n\005topic\030\002 \001(\t\022\022\n\nconsumerId\030\003 \001(\003\"b" +
      "\n\034GetMessageFromBrokerResponse\022\013\n\003ack\030\001 " +
      "\001(\010\022\013\n\003res\030\002 \001(\t\022\027\n\006status\030\003 \001(\0132\007.Statu" +
      "s\022\017\n\007message\030\004 \001(\t\"7\n\022CreateTopicRequest" +
      "\022\r\n\005topic\030\001 \001(\t\022\022\n\nproducerId\030\002 \001(\003\"H\n\023C" +
      "reateTopicResponse\022\013\n\003ack\030\001 \001(\010\022\013\n\003res\030\002" +
      " \001(\t\022\027\n\006status\030\003 \001(\0132\007.Status2\363\001\n\rBroker" +
      "Service\022O\n\022SendMessage2Broker\022\032.SendMess" +
      "age2BrokerRequest\032\033.SendMessage2BrokerRe" +
      "sponse\"\000\022U\n\024GetMessageFromBroker\022\034.GetMe" +
      "ssageFromBrokerRequest\032\035.GetMessageFromB" +
      "rokerResponse\"\000\022:\n\013CreateTopic\022\023.CreateT" +
      "opicRequest\032\024.CreateTopicResponse\"\000B\'\n\032o" +
      "rg.catmq.protocol.serviceP\001\210\001\001\240\001\001\330\001\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.catmq.protocol.definition.Definition.getDescriptor(),
        });
    internal_static_SendMessage2BrokerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SendMessage2BrokerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendMessage2BrokerRequest_descriptor,
        new java.lang.String[] { "Message", "Topic", "ProducerId", });
    internal_static_SendMessage2BrokerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SendMessage2BrokerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendMessage2BrokerResponse_descriptor,
        new java.lang.String[] { "Ack", "Res", "Status", });
    internal_static_GetMessageFromBrokerRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetMessageFromBrokerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetMessageFromBrokerRequest_descriptor,
        new java.lang.String[] { "Message", "Topic", "ConsumerId", });
    internal_static_GetMessageFromBrokerResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetMessageFromBrokerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetMessageFromBrokerResponse_descriptor,
        new java.lang.String[] { "Ack", "Res", "Status", "Message", });
    internal_static_CreateTopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CreateTopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateTopicRequest_descriptor,
        new java.lang.String[] { "Topic", "ProducerId", });
    internal_static_CreateTopicResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CreateTopicResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateTopicResponse_descriptor,
        new java.lang.String[] { "Ack", "Res", "Status", });
    org.catmq.protocol.definition.Definition.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
