// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.catmq.protocol.service;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendMessage2BrokerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendMessage2BrokerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendMessage2BrokerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendMessage2BrokerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetMessageFromBrokerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetMessageFromBrokerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetMessageFromBrokerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetMessageFromBrokerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\032\020definition.proto\",\n\031Sen" +
      "dMessage2BrokerRequest\022\017\n\007message\030\001 \001(\t\"" +
      "O\n\032SendMessage2BrokerResponse\022\013\n\003ack\030\001 \001" +
      "(\010\022\013\n\003res\030\002 \001(\t\022\027\n\006status\030\003 \001(\0132\007.Status" +
      "\".\n\033GetMessageFromBrokerRequest\022\017\n\007messa" +
      "ge\030\001 \001(\t\"Q\n\034GetMessageFromBrokerResponse" +
      "\022\013\n\003ack\030\001 \001(\010\022\013\n\003res\030\002 \001(\t\022\027\n\006status\030\003 \001" +
      "(\0132\007.Status2\267\001\n\rBrokerService\022O\n\022SendMes" +
      "sage2Broker\022\032.SendMessage2BrokerRequest\032" +
      "\033.SendMessage2BrokerResponse\"\000\022U\n\024GetMes" +
      "sageFromBroker\022\034.GetMessageFromBrokerReq" +
      "uest\032\035.GetMessageFromBrokerResponse\"\000B\'\n" +
      "\032org.catmq.protocol.serviceP\001\210\001\001\240\001\001\330\001\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.catmq.protocol.definition.Definition.getDescriptor(),
        });
    internal_static_SendMessage2BrokerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SendMessage2BrokerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendMessage2BrokerRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_SendMessage2BrokerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SendMessage2BrokerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendMessage2BrokerResponse_descriptor,
        new java.lang.String[] { "Ack", "Res", "Status", });
    internal_static_GetMessageFromBrokerRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetMessageFromBrokerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetMessageFromBrokerRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_GetMessageFromBrokerResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetMessageFromBrokerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetMessageFromBrokerResponse_descriptor,
        new java.lang.String[] { "Ack", "Res", "Status", });
    org.catmq.protocol.definition.Definition.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
