// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.catmq.protocol.service;

/**
 * Protobuf service {@code StorerService}
 */
public  abstract class StorerService
    implements com.google.protobuf.Service {
  protected StorerService() {}

  public interface Interface {
    /**
     * <code>rpc SendMessage2Storer(.SendMessage2StorerRequest) returns (.SendMessage2StorerResponse);</code>
     */
    public abstract void sendMessage2Storer(
        com.google.protobuf.RpcController controller,
        org.catmq.protocol.service.SendMessage2StorerRequest request,
        com.google.protobuf.RpcCallback<org.catmq.protocol.service.SendMessage2StorerResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new StorerService() {
      @java.lang.Override
      public  void sendMessage2Storer(
          com.google.protobuf.RpcController controller,
          org.catmq.protocol.service.SendMessage2StorerRequest request,
          com.google.protobuf.RpcCallback<org.catmq.protocol.service.SendMessage2StorerResponse> done) {
        impl.sendMessage2Storer(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.sendMessage2Storer(controller, (org.catmq.protocol.service.SendMessage2StorerRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return org.catmq.protocol.service.SendMessage2StorerRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return org.catmq.protocol.service.SendMessage2StorerResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc SendMessage2Storer(.SendMessage2StorerRequest) returns (.SendMessage2StorerResponse);</code>
   */
  public abstract void sendMessage2Storer(
      com.google.protobuf.RpcController controller,
      org.catmq.protocol.service.SendMessage2StorerRequest request,
      com.google.protobuf.RpcCallback<org.catmq.protocol.service.SendMessage2StorerResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return org.catmq.protocol.service.Service.getDescriptor().getServices().get(1);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.sendMessage2Storer(controller, (org.catmq.protocol.service.SendMessage2StorerRequest)request,
          com.google.protobuf.RpcUtil.<org.catmq.protocol.service.SendMessage2StorerResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return org.catmq.protocol.service.SendMessage2StorerRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return org.catmq.protocol.service.SendMessage2StorerResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends org.catmq.protocol.service.StorerService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void sendMessage2Storer(
        com.google.protobuf.RpcController controller,
        org.catmq.protocol.service.SendMessage2StorerRequest request,
        com.google.protobuf.RpcCallback<org.catmq.protocol.service.SendMessage2StorerResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        org.catmq.protocol.service.SendMessage2StorerResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          org.catmq.protocol.service.SendMessage2StorerResponse.class,
          org.catmq.protocol.service.SendMessage2StorerResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public org.catmq.protocol.service.SendMessage2StorerResponse sendMessage2Storer(
        com.google.protobuf.RpcController controller,
        org.catmq.protocol.service.SendMessage2StorerRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public org.catmq.protocol.service.SendMessage2StorerResponse sendMessage2Storer(
        com.google.protobuf.RpcController controller,
        org.catmq.protocol.service.SendMessage2StorerRequest request)
        throws com.google.protobuf.ServiceException {
      return (org.catmq.protocol.service.SendMessage2StorerResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        org.catmq.protocol.service.SendMessage2StorerResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:StorerService)
}

