// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Produce.proto

package org.catmq.protocol.produce;

public final class Produce {
  private Produce() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendMessage2BrokerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendMessage2BrokerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendMessage2BrokerReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendMessage2BrokerReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendMessage2StorerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendMessage2StorerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendMessage2StorerReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendMessage2StorerReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rProduce.proto\032\017Structure.proto\";\n\031Send" +
      "Message2BrokerRequest\022\r\n\005topic\030\001 \001(\t\022\017\n\007" +
      "message\030\002 \001(\t\"3\n\027SendMessage2BrokerReply" +
      "\022\013\n\003ack\030\001 \001(\010\022\013\n\003res\030\002 \001(\t\"2\n\031SendMessag" +
      "e2StorerRequest\022\025\n\004info\030\001 \001(\0132\007.KvPair\"&" +
      "\n\027SendMessage2StorerReply\022\013\n\003ack\030\001 \001(\0102^" +
      "\n\016ProduceService\022L\n\022SendMessage2Broker\022\032" +
      ".SendMessage2BrokerRequest\032\030.SendMessage" +
      "2BrokerReply\"\000B!\n\032org.catmq.protocol.pro" +
      "duceP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.catmq.protocol.structure.Structure.getDescriptor(),
        });
    internal_static_SendMessage2BrokerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SendMessage2BrokerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendMessage2BrokerRequest_descriptor,
        new java.lang.String[] { "Topic", "Message", });
    internal_static_SendMessage2BrokerReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SendMessage2BrokerReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendMessage2BrokerReply_descriptor,
        new java.lang.String[] { "Ack", "Res", });
    internal_static_SendMessage2StorerRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SendMessage2StorerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendMessage2StorerRequest_descriptor,
        new java.lang.String[] { "Info", });
    internal_static_SendMessage2StorerReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SendMessage2StorerReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendMessage2StorerReply_descriptor,
        new java.lang.String[] { "Ack", });
    org.catmq.protocol.structure.Structure.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
