// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Produce.proto

package org.catmq.protocol.produce;

public interface SendMessage2StorerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendMessage2StorerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.KvPair info = 1;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>.KvPair info = 1;</code>
   * @return The info.
   */
  org.catmq.protocol.structure.Structure.KvPair getInfo();
  /**
   * <code>.KvPair info = 1;</code>
   */
  org.catmq.protocol.structure.Structure.KvPairOrBuilder getInfoOrBuilder();
}
