// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Produce.proto

package org.catmq.protocol.produce;

public interface SendMessage2StorerReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendMessage2StorerReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ack = 1;</code>
   * @return The ack.
   */
  boolean getAck();
}
