// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Consume.proto

package org.catmq.protocol.consume;

public final class Consume {
  private Consume() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetMessageFromBrokerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetMessageFromBrokerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetMessageFromBrokerReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetMessageFromBrokerReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rConsume.proto\"=\n\033GetMessageFromBrokerR" +
      "equest\022\r\n\005topic\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"5" +
      "\n\031GetMessageFromBrokerReply\022\013\n\003ack\030\001 \001(\010" +
      "\022\013\n\003res\030\002 \001(\t2d\n\016ConsumeService\022R\n\024GetMe" +
      "ssageFromBroker\022\034.GetMessageFromBrokerRe" +
      "quest\032\032.GetMessageFromBrokerReply\"\000B!\n\032o" +
      "rg.catmq.protocol.consumeP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetMessageFromBrokerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetMessageFromBrokerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetMessageFromBrokerRequest_descriptor,
        new java.lang.String[] { "Topic", "Message", });
    internal_static_GetMessageFromBrokerReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetMessageFromBrokerReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetMessageFromBrokerReply_descriptor,
        new java.lang.String[] { "Ack", "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
