// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Consume.proto

package org.catmq.protocol.consume;

public interface GetMessageFromBrokerReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetMessageFromBrokerReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ack = 1;</code>
   * @return The ack.
   */
  boolean getAck();

  /**
   * <code>string res = 2;</code>
   * @return The res.
   */
  java.lang.String getRes();
  /**
   * <code>string res = 2;</code>
   * @return The bytes for res.
   */
  com.google.protobuf.ByteString
      getResBytes();
}
