// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Consume.proto

package org.catmq.protocol.consume;

/**
 * Protobuf type {@code GetMessageFromBrokerReply}
 */
public final class GetMessageFromBrokerReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetMessageFromBrokerReply)
    GetMessageFromBrokerReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetMessageFromBrokerReply.newBuilder() to construct.
  private GetMessageFromBrokerReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetMessageFromBrokerReply() {
    res_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetMessageFromBrokerReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.catmq.protocol.consume.Consume.internal_static_GetMessageFromBrokerReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.catmq.protocol.consume.Consume.internal_static_GetMessageFromBrokerReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.catmq.protocol.consume.GetMessageFromBrokerReply.class, org.catmq.protocol.consume.GetMessageFromBrokerReply.Builder.class);
  }

  public static final int ACK_FIELD_NUMBER = 1;
  private boolean ack_;
  /**
   * <code>bool ack = 1;</code>
   * @return The ack.
   */
  @java.lang.Override
  public boolean getAck() {
    return ack_;
  }

  public static final int RES_FIELD_NUMBER = 2;
  private volatile java.lang.Object res_;
  /**
   * <code>string res = 2;</code>
   * @return The res.
   */
  @java.lang.Override
  public java.lang.String getRes() {
    java.lang.Object ref = res_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      res_ = s;
      return s;
    }
  }
  /**
   * <code>string res = 2;</code>
   * @return The bytes for res.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResBytes() {
    java.lang.Object ref = res_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      res_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ack_ != false) {
      output.writeBool(1, ack_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(res_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, res_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ack_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, ack_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(res_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, res_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.catmq.protocol.consume.GetMessageFromBrokerReply)) {
      return super.equals(obj);
    }
    org.catmq.protocol.consume.GetMessageFromBrokerReply other = (org.catmq.protocol.consume.GetMessageFromBrokerReply) obj;

    if (getAck()
        != other.getAck()) return false;
    if (!getRes()
        .equals(other.getRes())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAck());
    hash = (37 * hash) + RES_FIELD_NUMBER;
    hash = (53 * hash) + getRes().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.catmq.protocol.consume.GetMessageFromBrokerReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.catmq.protocol.consume.GetMessageFromBrokerReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.catmq.protocol.consume.GetMessageFromBrokerReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.catmq.protocol.consume.GetMessageFromBrokerReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.catmq.protocol.consume.GetMessageFromBrokerReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.catmq.protocol.consume.GetMessageFromBrokerReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.catmq.protocol.consume.GetMessageFromBrokerReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.catmq.protocol.consume.GetMessageFromBrokerReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.catmq.protocol.consume.GetMessageFromBrokerReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.catmq.protocol.consume.GetMessageFromBrokerReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.catmq.protocol.consume.GetMessageFromBrokerReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.catmq.protocol.consume.GetMessageFromBrokerReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.catmq.protocol.consume.GetMessageFromBrokerReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetMessageFromBrokerReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetMessageFromBrokerReply)
      org.catmq.protocol.consume.GetMessageFromBrokerReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.catmq.protocol.consume.Consume.internal_static_GetMessageFromBrokerReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.catmq.protocol.consume.Consume.internal_static_GetMessageFromBrokerReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.catmq.protocol.consume.GetMessageFromBrokerReply.class, org.catmq.protocol.consume.GetMessageFromBrokerReply.Builder.class);
    }

    // Construct using org.catmq.protocol.consume.GetMessageFromBrokerReply.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ack_ = false;

      res_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.catmq.protocol.consume.Consume.internal_static_GetMessageFromBrokerReply_descriptor;
    }

    @java.lang.Override
    public org.catmq.protocol.consume.GetMessageFromBrokerReply getDefaultInstanceForType() {
      return org.catmq.protocol.consume.GetMessageFromBrokerReply.getDefaultInstance();
    }

    @java.lang.Override
    public org.catmq.protocol.consume.GetMessageFromBrokerReply build() {
      org.catmq.protocol.consume.GetMessageFromBrokerReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.catmq.protocol.consume.GetMessageFromBrokerReply buildPartial() {
      org.catmq.protocol.consume.GetMessageFromBrokerReply result = new org.catmq.protocol.consume.GetMessageFromBrokerReply(this);
      result.ack_ = ack_;
      result.res_ = res_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.catmq.protocol.consume.GetMessageFromBrokerReply) {
        return mergeFrom((org.catmq.protocol.consume.GetMessageFromBrokerReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.catmq.protocol.consume.GetMessageFromBrokerReply other) {
      if (other == org.catmq.protocol.consume.GetMessageFromBrokerReply.getDefaultInstance()) return this;
      if (other.getAck() != false) {
        setAck(other.getAck());
      }
      if (!other.getRes().isEmpty()) {
        res_ = other.res_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              ack_ = input.readBool();

              break;
            } // case 8
            case 18: {
              res_ = input.readStringRequireUtf8();

              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private boolean ack_ ;
    /**
     * <code>bool ack = 1;</code>
     * @return The ack.
     */
    @java.lang.Override
    public boolean getAck() {
      return ack_;
    }
    /**
     * <code>bool ack = 1;</code>
     * @param value The ack to set.
     * @return This builder for chaining.
     */
    public Builder setAck(boolean value) {
      
      ack_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool ack = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAck() {
      
      ack_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object res_ = "";
    /**
     * <code>string res = 2;</code>
     * @return The res.
     */
    public java.lang.String getRes() {
      java.lang.Object ref = res_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        res_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string res = 2;</code>
     * @return The bytes for res.
     */
    public com.google.protobuf.ByteString
        getResBytes() {
      java.lang.Object ref = res_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        res_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string res = 2;</code>
     * @param value The res to set.
     * @return This builder for chaining.
     */
    public Builder setRes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      res_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string res = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRes() {
      
      res_ = getDefaultInstance().getRes();
      onChanged();
      return this;
    }
    /**
     * <code>string res = 2;</code>
     * @param value The bytes for res to set.
     * @return This builder for chaining.
     */
    public Builder setResBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      res_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetMessageFromBrokerReply)
  }

  // @@protoc_insertion_point(class_scope:GetMessageFromBrokerReply)
  private static final org.catmq.protocol.consume.GetMessageFromBrokerReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.catmq.protocol.consume.GetMessageFromBrokerReply();
  }

  public static org.catmq.protocol.consume.GetMessageFromBrokerReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetMessageFromBrokerReply>
      PARSER = new com.google.protobuf.AbstractParser<GetMessageFromBrokerReply>() {
    @java.lang.Override
    public GetMessageFromBrokerReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetMessageFromBrokerReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetMessageFromBrokerReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.catmq.protocol.consume.GetMessageFromBrokerReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

