// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package org.catmq.protocol.definition;

/**
 * Protobuf enum {@code ChecksumType}
 */
public enum ChecksumType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DIGEST_TYPE_UNSPECIFIED = 0;</code>
   */
  DIGEST_TYPE_UNSPECIFIED(0),
  /**
   * <pre>
   * CRC algorithm achieves goal of detecting random data error with lowest
   * computation overhead.
   * </pre>
   *
   * <code>CRC32 = 1;</code>
   */
  CRC32(1),
  /**
   * <pre>
   * MD5 algorithm achieves good balance between collision rate and computation
   * overhead.
   * </pre>
   *
   * <code>MD5 = 2;</code>
   */
  MD5(2),
  /**
   * <pre>
   * SHA-family has substantially fewer collision with fair amount of
   * computation.
   * </pre>
   *
   * <code>SHA1 = 3;</code>
   */
  SHA1(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>DIGEST_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int DIGEST_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * CRC algorithm achieves goal of detecting random data error with lowest
   * computation overhead.
   * </pre>
   *
   * <code>CRC32 = 1;</code>
   */
  public static final int CRC32_VALUE = 1;
  /**
   * <pre>
   * MD5 algorithm achieves good balance between collision rate and computation
   * overhead.
   * </pre>
   *
   * <code>MD5 = 2;</code>
   */
  public static final int MD5_VALUE = 2;
  /**
   * <pre>
   * SHA-family has substantially fewer collision with fair amount of
   * computation.
   * </pre>
   *
   * <code>SHA1 = 3;</code>
   */
  public static final int SHA1_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ChecksumType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ChecksumType forNumber(int value) {
    switch (value) {
      case 0: return DIGEST_TYPE_UNSPECIFIED;
      case 1: return CRC32;
      case 2: return MD5;
      case 3: return SHA1;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ChecksumType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ChecksumType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ChecksumType>() {
          public ChecksumType findValueByNumber(int number) {
            return ChecksumType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.catmq.protocol.definition.Definition.getDescriptor().getEnumTypes().get(3);
  }

  private static final ChecksumType[] VALUES = values();

  public static ChecksumType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ChecksumType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ChecksumType)
}

