// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package org.catmq.protocol.definition;

public interface ChecksumOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Checksum)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ChecksumType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.ChecksumType type = 1;</code>
   * @return The type.
   */
  org.catmq.protocol.definition.ChecksumType getType();

  /**
   * <code>string body = 2;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 2;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
