// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package org.catmq.protocol.definition;

public final class Definition {
  private Definition() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Checksum_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Checksum_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SystemProperties_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SystemProperties_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KvPair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KvPair_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Status_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020definition.proto\032\037google/protobuf/time" +
      "stamp.proto\032\036google/protobuf/duration.pr" +
      "oto\"5\n\010Checksum\022\033\n\004type\030\001 \001(\0162\r.Checksum" +
      "Type\022\014\n\004body\030\002 \001(\t\"\375\006\n\020SystemProperties\022" +
      "\020\n\003tag\030\001 \001(\tH\000\210\001\001\022\014\n\004keys\030\002 \003(\t\022\022\n\nmessa" +
      "ge_id\030\003 \001(\t\022\036\n\013body_digest\030\004 \001(\0132\t.Check" +
      "sum\022 \n\rbody_encoding\030\005 \001(\0162\t.Encoding\022\"\n" +
      "\014message_type\030\006 \001(\0162\014.MessageType\0222\n\016bor" +
      "n_timestamp\030\007 \001(\0132\032.google.protobuf.Time" +
      "stamp\022\021\n\tborn_host\030\010 \001(\t\0228\n\017store_timest" +
      "amp\030\t \001(\0132\032.google.protobuf.TimestampH\001\210" +
      "\001\001\022\022\n\nstore_host\030\n \001(\t\022;\n\022delivery_times" +
      "tamp\030\013 \001(\0132\032.google.protobuf.TimestampH\002" +
      "\210\001\001\022\033\n\016receipt_handle\030\014 \001(\tH\003\210\001\001\022\020\n\010queu" +
      "e_id\030\r \001(\005\022\031\n\014queue_offset\030\016 \001(\003H\004\210\001\001\022:\n" +
      "\022invisible_duration\030\017 \001(\0132\031.google.proto" +
      "buf.DurationH\005\210\001\001\022\035\n\020delivery_attempt\030\020 " +
      "\001(\005H\006\210\001\001\022\032\n\rmessage_group\030\021 \001(\tH\007\210\001\001\022\032\n\r" +
      "trace_context\030\022 \001(\tH\010\210\001\001\022N\n&orphaned_tra" +
      "nsaction_recovery_duration\030\023 \001(\0132\031.googl" +
      "e.protobuf.DurationH\t\210\001\001B\006\n\004_tagB\022\n\020_sto" +
      "re_timestampB\025\n\023_delivery_timestampB\021\n\017_" +
      "receipt_handleB\017\n\r_queue_offsetB\025\n\023_invi" +
      "sible_durationB\023\n\021_delivery_attemptB\020\n\016_" +
      "message_groupB\020\n\016_trace_contextB)\n\'_orph" +
      "aned_transaction_recovery_duration\"$\n\006Kv" +
      "Pair\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\".\n\006Stat" +
      "us\022\023\n\004code\030\001 \001(\0162\005.Code\022\017\n\007message\030\002 \001(\t" +
      "*W\n\nPermission\022\032\n\026PERMISSION_UNSPECIFIED" +
      "\020\000\022\010\n\004NONE\020\001\022\010\n\004READ\020\002\022\t\n\005WRITE\020\003\022\016\n\nREA" +
      "D_WRITE\020\004*]\n\013MessageType\022\034\n\030MESSAGE_TYPE" +
      "_UNSPECIFIED\020\000\022\n\n\006NORMAL\020\001\022\010\n\004FIFO\020\002\022\t\n\005" +
      "DELAY\020\003\022\017\n\013TRANSACTION\020\004*[\n\010Encoding\022\030\n\024" +
      "ENCODING_UNSPECIFIED\020\000\022\014\n\010IDENTITY\020\001\022\010\n\004" +
      "GZIP\020\002\022\007\n\003LZ4\020\003\022\010\n\004ZSTD\020\004\022\n\n\006SNAPPY\020\005*I\n" +
      "\014ChecksumType\022\033\n\027DIGEST_TYPE_UNSPECIFIED" +
      "\020\000\022\t\n\005CRC32\020\001\022\007\n\003MD5\020\002\022\010\n\004SHA1\020\003*\342\t\n\004Cod" +
      "e\022\024\n\020CODE_UNSPECIFIED\020\000\022\010\n\002OK\020\240\234\001\022\026\n\020MUL" +
      "TIPLE_RESULTS\020\260\352\001\022\021\n\013BAD_REQUEST\020\300\270\002\022\032\n\024" +
      "ILLEGAL_ACCESS_POINT\020\301\270\002\022\023\n\rILLEGAL_TOPI" +
      "C\020\302\270\002\022\034\n\026ILLEGAL_CONSUMER_GROUP\020\303\270\002\022\031\n\023I" +
      "LLEGAL_MESSAGE_TAG\020\304\270\002\022\031\n\023ILLEGAL_MESSAG" +
      "E_KEY\020\305\270\002\022\033\n\025ILLEGAL_MESSAGE_GROUP\020\306\270\002\022\"" +
      "\n\034ILLEGAL_MESSAGE_PROPERTY_KEY\020\307\270\002\022\034\n\026IN" +
      "VALID_TRANSACTION_ID\020\310\270\002\022\030\n\022ILLEGAL_MESS" +
      "AGE_ID\020\311\270\002\022\037\n\031ILLEGAL_FILTER_EXPRESSION\020" +
      "\312\270\002\022\034\n\026ILLEGAL_INVISIBLE_TIME\020\313\270\002\022\033\n\025ILL" +
      "EGAL_DELIVERY_TIME\020\314\270\002\022\034\n\026INVALID_RECEIP" +
      "T_HANDLE\020\315\270\002\022)\n#MESSAGE_PROPERTY_CONFLIC" +
      "T_WITH_TYPE\020\316\270\002\022\036\n\030UNRECOGNIZED_CLIENT_T" +
      "YPE\020\317\270\002\022\027\n\021MESSAGE_CORRUPTED\020\320\270\002\022\030\n\022CLIE" +
      "NT_ID_REQUIRED\020\321\270\002\022\022\n\014UNAUTHORIZED\020\244\271\002\022\026" +
      "\n\020PAYMENT_REQUIRED\020\210\272\002\022\017\n\tFORBIDDEN\020\354\272\002\022" +
      "\017\n\tNOT_FOUND\020\320\273\002\022\027\n\021MESSAGE_NOT_FOUND\020\321\273" +
      "\002\022\025\n\017TOPIC_NOT_FOUND\020\322\273\002\022\036\n\030CONSUMER_GRO" +
      "UP_NOT_FOUND\020\323\273\002\022\025\n\017REQUEST_TIMEOUT\020\340\276\002\022" +
      "\027\n\021PAYLOAD_TOO_LARGE\020\324\302\002\022\034\n\026MESSAGE_BODY" +
      "_TOO_LARGE\020\325\302\002\022\031\n\023PRECONDITION_FAILED\020\260\316" +
      "\002\022\027\n\021TOO_MANY_REQUESTS\020\224\317\002\022%\n\037REQUEST_HE" +
      "ADER_FIELDS_TOO_LARGE\020\334\320\002\022\"\n\034MESSAGE_PRO" +
      "PERTIES_TOO_LARGE\020\335\320\002\022\024\n\016INTERNAL_ERROR\020" +
      "\320\206\003\022\033\n\025INTERNAL_SERVER_ERROR\020\321\206\003\022\026\n\020HA_N" +
      "OT_AVAILABLE\020\322\206\003\022\025\n\017NOT_IMPLEMENTED\020\264\207\003\022" +
      "\023\n\rPROXY_TIMEOUT\020\340\211\003\022 \n\032MASTER_PERSISTEN" +
      "CE_TIMEOUT\020\341\211\003\022\037\n\031SLAVE_PERSISTENCE_TIME" +
      "OUT\020\342\211\003\022\021\n\013UNSUPPORTED\020\304\212\003\022\031\n\023VERSION_UN" +
      "SUPPORTED\020\305\212\003\022%\n\037VERIFY_FIFO_MESSAGE_UNS" +
      "UPPORTED\020\306\212\003\022\037\n\031FAILED_TO_CONSUME_MESSAG" +
      "E\020\340\324\003B*\n\035org.catmq.protocol.definitionP\001" +
      "\210\001\001\240\001\001\330\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
        });
    internal_static_Checksum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Checksum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Checksum_descriptor,
        new java.lang.String[] { "Type", "Body", });
    internal_static_SystemProperties_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SystemProperties_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SystemProperties_descriptor,
        new java.lang.String[] { "Tag", "Keys", "MessageId", "BodyDigest", "BodyEncoding", "MessageType", "BornTimestamp", "BornHost", "StoreTimestamp", "StoreHost", "DeliveryTimestamp", "ReceiptHandle", "QueueId", "QueueOffset", "InvisibleDuration", "DeliveryAttempt", "MessageGroup", "TraceContext", "OrphanedTransactionRecoveryDuration", "Tag", "StoreTimestamp", "DeliveryTimestamp", "ReceiptHandle", "QueueOffset", "InvisibleDuration", "DeliveryAttempt", "MessageGroup", "TraceContext", "OrphanedTransactionRecoveryDuration", });
    internal_static_KvPair_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_KvPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KvPair_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Status_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Status_descriptor,
        new java.lang.String[] { "Code", "Message", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
