// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: definition.proto

package org.catmq.protocol.definition;

/**
 * Protobuf enum {@code Encoding}
 */
public enum Encoding
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ENCODING_UNSPECIFIED = 0;</code>
   */
  ENCODING_UNSPECIFIED(0),
  /**
   * <code>IDENTITY = 1;</code>
   */
  IDENTITY(1),
  /**
   * <code>GZIP = 2;</code>
   */
  GZIP(2),
  /**
   * <code>LZ4 = 3;</code>
   */
  LZ4(3),
  /**
   * <code>ZSTD = 4;</code>
   */
  ZSTD(4),
  /**
   * <code>SNAPPY = 5;</code>
   */
  SNAPPY(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ENCODING_UNSPECIFIED = 0;</code>
   */
  public static final int ENCODING_UNSPECIFIED_VALUE = 0;
  /**
   * <code>IDENTITY = 1;</code>
   */
  public static final int IDENTITY_VALUE = 1;
  /**
   * <code>GZIP = 2;</code>
   */
  public static final int GZIP_VALUE = 2;
  /**
   * <code>LZ4 = 3;</code>
   */
  public static final int LZ4_VALUE = 3;
  /**
   * <code>ZSTD = 4;</code>
   */
  public static final int ZSTD_VALUE = 4;
  /**
   * <code>SNAPPY = 5;</code>
   */
  public static final int SNAPPY_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Encoding valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Encoding forNumber(int value) {
    switch (value) {
      case 0: return ENCODING_UNSPECIFIED;
      case 1: return IDENTITY;
      case 2: return GZIP;
      case 3: return LZ4;
      case 4: return ZSTD;
      case 5: return SNAPPY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Encoding>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Encoding> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Encoding>() {
          public Encoding findValueByNumber(int number) {
            return Encoding.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.catmq.protocol.definition.Definition.getDescriptor().getEnumTypes().get(2);
  }

  private static final Encoding[] VALUES = values();

  public static Encoding valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Encoding(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Encoding)
}

